### ISSUE TITLE
Issue with create() API

### ISSUE THREAD

**Issue by zerebral** [dittach/loopback-connector-riak#3]
For any documents the connector tries to insert (with or without an ID) the app throws the following error - 

Riak connector id conflict during create for id 7b92eff0-0755-11e5-9e14-c9e6f4ae8c14
  express:router restRemoteMethodNotFound  : /api/comment_likes +23ms
  express:router restUrlNotFound  : /api/comment_likes +0ms
  express:router restErrorHandler  : /api/comment_likes +0ms
  strong-remoting:rest-adapter Error in POST /comment_likes: Error: id conflict during create for id 7b92eff0-0755-11e5-9e14-c9e6f4ae8c14
    at conflictError (/home/zerebral2/projects/topic_backend/node_modules/loopback-connector-riak/lib/api/create.js:43:17)
    at /home/zerebral2/projects/topic_backend/node_modules/loopback-connector-riak/lib/api/create.js:30:35
    at /home/zerebral2/projects/topic_backend/node_modules/loopback-connector-riak/node_modules/riak-js/lib/http-client.js:116:7
    at IncomingMessage.<anonymous> (/home/zerebral2/projects/topic_backend/node_modules/loopback-connector-riak/node_modules/riak-js/lib/http-request.js:146:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at /home/zerebral2/projects/topic_backend/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/home/zerebral2/projects/topic_backend/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15) +11ms
  compression gzip compression +25s

**Comment by behrad** [comment]
the same here, trying with 0.1.1 :(

**Comment by behrad** [comment]
any news on this?

**Comment by behrad** [comment]
@onyxrev

**Comment by onyxrev** [comment]
@behrad I've got a branch that is based on the relatively new official basho client rather than on the older riakjs project. It's working for our use-cases so far and it supports Node v0.12. Some time in the next couple of weeks I'd like to merge it in.  Here's an example config:

```javascript
{
  "db": {
    "name": "db",
    "connector": "riak",
    "host": [
      "riak1.local.staging.com:8087",
      "riak2.local.staging.com:8087",
      "riak3.local.staging.com:8087",
      "riak4.local.staging.com:8087",
      "riak5.local.staging.com:8087"
    ]
  }
}
```

https://github.com/dittach/loopback-connector-riak/tree/official_basho_client

**Comment by behrad** [comment]
thank you @onyxrev , with `offical_basho_client` branch I'm no able to Create/Get my model, hoping to see this merged soon :)

Can you give me an example how to use loopback `find` on my model.
Should I define a new riak type/riak bucket?
and how should I define my index on riak-side?
I receive a 
```
<0.2193.0>@yz_pb_search:maybe_process:107 {solr_error,{400,"http://localhost:8093/internal_solr/message/select",<<"{\"error\":{\"msg\":\"can not sort on a field which is neither indexed nor has doc values: id\",\"code\":400}}\n">>}}
```

**Comment by onyxrev** [comment]
@behrad FYI we're now on v1.0 with the official Basho client. You need to specify an index in Riak manually. See http://docs.basho.com/riak/latest/dev/using/search/

There are some example schemas in the test/schemas directory.
